// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "moBJ7FZWCzpz8vpm6wInSS1v2EgCHFFxZZcnYr1u0jIoIWV6Z2DnJVLxxrbh08DrSXwQXl";
}
}
}

